# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build service and publish npm package

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      version:
        required: true
        type: string
      packaging:
        type: string
        required: false
        default: 'native-image'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github", "username": "${{ secrets.MAVEN_USER }}", "password": "${{ secrets.MAVEN_TOKEN }}"}]'
          repositories: '[{"id":"github","name":"github","url":"https://maven.pkg.github.com/opendonationassistant/oda-libraries","snapshots":{"enabled":true}}]'

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build with Maven
        run: "mvn -B -q clean package -Dpackaging=${{ inputs.packaging }} -DskipTests"

      - name: Install npm package
        run: npm install
        working-directory: "target/generated-sources/openapi/"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
          package: "target/generated-sources/openapi/"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/opendonationassistant/oda-${{ inputs.service }}:${{ inputs.version }}
