# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy service

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying new version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: 'sh ~/update-${{ inputs.service }}.sh ${{ inputs.version }}'
