name: Publish package to GitHub Packages
on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish commons
        run: mvn --batch-mode clean install -DbuildNumber=${{ github.RUN_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish commons
        run: mvn --batch-mode deploy -pl 'commons ' -DbuildNumber=${{ github.RUN_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish rabbit-conf
        run: mvn --batch-mode deploy -pl 'rabbit-conf' -DbuildNumber=${{ github.RUN_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
